include:
  - project: 'flexypw/infrastructure'
    file: '/ci-templates/monorepo-templates.yml'

variables:
  ADMIN_API_SERVICE: blp-admin-api
  ADMIN_API_DOMAIN: admin.api.blp.flexy.pw
  MOBILE_API_SERVICE: blp-mobile-api
  MOBILE_API_DOMAIN: mobile.api.blp.flexy.pw
  INTEGRATION_API_SERVICE: blp-integration-api
  INTEGRATION_API_DOMAIN: integration.api.blp.flexy.pw
  ADMIN_SERVICE: blp-admin
  ADMIN_DOMAIN: admin.blp.flexy.pw

artifacts:
  image: node:15-alpine
  stage: Artifacts
  script:
    - yarn install
    - NEXT_PUBLIC_BASE_API_URL="https://admin.api.blp.flexy.pw/api" npm run build admin -- --prod
    - npm run build api  -- --prod
    - npm run build mobile-api -- --prod
    - npm run build integration-api -- --prod
  only:
    - web
  artifacts:
    paths:
      - dist
    expire_in: 30 days

admin-api:build:
  extends: .api-base-build
  variables:
    APP_NAME: api
    SERVICE_NAME: $ADMIN_API_SERVICE
    SERVICE_DOMAIN: $ADMIN_API_DOMAIN
  needs:
    - job: artifacts
      artifacts: true

admin-api:deploy:
  extends: .deploy-new
  resource_group: deploy
  script:
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no deploy@$DEPLOYMENT_IP "
      docker run
      --name ${SERVICE_NAME}
      --network=flexy-infra
      --env DB_HOST=\"business-loyalty-program-db\"
      --env DB_PORT=\"5432\"
      --env DB_USERNAME=\"business-loyalty-program-user\"
      --env DB_PASSWORD=\"password\"
      --env DB_NAME=\"business-loyalty-program\"
      --env JWT_MNEMONIC=\"${JWT_MNEMONIC}\"
      --env SALT=\"${SALT}\"
      --env MINIO_ENDPOINT=\"${MINIO_ENDPOINT}\"
      --env MINIO_PORT=\"${MINIO_PORT}\"
      --env MINIO_ACCESS_KEY=\"${MINIO_ACCESS_KEY}\"
      --env MINIO_SECRET_KEY=\"${MINIO_SECRET_KEY}\"
      --env MINIO_BUCKET=\"business-loyalty-program\"
      --env MINIO_BASE_URL=\"${MINIO_BASE_URL}\"
      --env DADATA_TOKEN=\"${DADATA_TOKEN}\"
      --env DADATA_BASEURL=\"${DADATA_BASEURL}\"
      --env ONE_SIGNAL_APP_ID=\"${ONE_SIGNAL_APP_ID}\"
      --env ONE_SIGNAL_TOKEN=\"${ONE_SIGNAL_TOKEN}\"
      -d ${IMAGE_PREFIX}/${SERVICE_NAME}
      "
  needs: ["admin-api:build"]
  variables:
    SERVICE_NAME: $ADMIN_API_SERVICE
    GIT_STRATEGY: none
  only:
    - web

mobile-api:build:
  extends: .api-base-build
  variables:
    APP_NAME: mobile-api
    SERVICE_NAME: $MOBILE_API_SERVICE
    SERVICE_DOMAIN: $MOBILE_API_DOMAIN
  needs:
    - job: artifacts
      artifacts: true

mobile-api:deploy:
  extends: .deploy-new
  resource_group: deploy
  script:
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no deploy@$DEPLOYMENT_IP "
      docker run
      --name ${SERVICE_NAME}
      --network=flexy-infra
      --env DB_HOST=\"business-loyalty-program-db\"
      --env DB_PORT=\"5432\"
      --env DB_USERNAME=\"business-loyalty-program-user\"
      --env DB_PASSWORD=\"password\"
      --env DB_NAME=\"business-loyalty-program\"
      --env JWT_MNEMONIC=\"${JWT_MNEMONIC}\"
      --env SALT=\"${SALT}\"
      --env MINIO_ENDPOINT=\"${MINIO_ENDPOINT}\"
      --env MINIO_PORT=\"${MINIO_PORT}\"
      --env MINIO_ACCESS_KEY=\"${MINIO_ACCESS_KEY}\"
      --env MINIO_SECRET_KEY=\"${MINIO_SECRET_KEY}\"
      --env MINIO_BUCKET=\"business-loyalty-program\"
      --env MINIO_BASE_URL=\"${MINIO_BASE_URL}\"
      --env REDIS_HOST=\"blp-redis\"
      --env REDIS_PORT=\"6379\"
      --env SMS_LOGIN=\"${SMS_LOGIN}\"
      --env SMS_PASSWORD=\"${SMS_PASSWORD}\"
      --env ONE_SIGNAL_APP_ID=\"${ONE_SIGNAL_APP_ID}\"
      --env ONE_SIGNAL_TOKEN=\"${ONE_SIGNAL_TOKEN}\"
      -d ${IMAGE_PREFIX}/${SERVICE_NAME}
      "
  needs: ["mobile-api:build"]
  variables:
    SERVICE_NAME: $MOBILE_API_SERVICE
    GIT_STRATEGY: none
  only:
    - web

integration-api:build:
  extends: .api-base-build
  variables:
    APP_NAME: integration-api
    SERVICE_NAME: $INTEGRATION_API_SERVICE
    SERVICE_DOMAIN: $INTEGRATION_API_DOMAIN
  needs:
    - job: artifacts
      artifacts: true

integration-api:deploy:
  extends: .deploy-new
  resource_group: deploy
  script:
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no deploy@$DEPLOYMENT_IP "
      docker run
      --name ${SERVICE_NAME}
      --network=flexy-infra
      --env DB_HOST=\"business-loyalty-program-db\"
      --env DB_PORT=\"5432\"
      --env DB_USERNAME=\"business-loyalty-program-user\"
      --env DB_PASSWORD=\"password\"
      --env DB_NAME=\"business-loyalty-program\"
      --env ONE_SIGNAL_APP_ID=\"${ONE_SIGNAL_APP_ID}\"
      --env ONE_SIGNAL_TOKEN=\"${ONE_SIGNAL_TOKEN}\"
      -d ${IMAGE_PREFIX}/${SERVICE_NAME}
      "
  needs: ["integration-api:build"]
  variables:
    SERVICE_NAME: $INTEGRATION_API_SERVICE
    GIT_STRATEGY: none
  only:
    - web

admin:build:
  extends: .client-base-build
  variables:
    APP_NAME: admin
    SERVICE_NAME: $ADMIN_SERVICE
    SERVICE_DOMAIN: $ADMIN_DOMAIN
  needs:
    - job: artifacts
      artifacts: true

admin:deploy:
  extends: .client-base-deploy
  resource_group: deploy
  needs: ["admin:build"]
  variables:
    SERVICE_NAME: $ADMIN_SERVICE
    API_SERVICE_NAME: $ADMIN_API_SERVICE
