nodeLinker: node-modules

npmRegistries:
  "https://gitlab.com/api/v4/packages/npm/":
    npmAlwaysAuth: true
    npmAuthToken: "${GITLAB_YARN_TOKEN}"

npmScopes:
  flexypw:
    npmRegistryServer: "https://gitlab.com/api/v4/packages/npm/"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
