version: '3.7'

services:
  business-loyalty-program-db:
    image: postgres:13
    restart: always
    container_name: business-loyalty-program-db
    networks:
      - flexy-infra
    environment:
      POSTGRES_DB: 'business-loyalty-program'
      POSTGRES_USER: 'business-loyalty-program-user'
      POSTGRES_PASSWORD: 'password'
    expose:
      - '5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
  blp-redis:
    image: "redis:alpine"
    restart: always
    container_name: blp-redis
    expose:
      - '6379'
networks:
  flexy-infra:
    external: true
